apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: my-quarkus-quick-start
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-mcombi-tenant/my-quarkus-quick-start/my-quarkus-quick-start@sha256:19cecee96c062048a4daf20f11b68bb8a3b282602258abd212b9c62b5b3cf37b
        name: my-java-quarkus
        resources: {}
status: {}
