apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: my-quarkus-quick-start
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-mcombi-tenant/my-quarkus-quick-start/my-quarkus-quick-start@sha256:1a7ad97968507942c99aa939a7225bc24842cc881831baa471fb4f593f1ce952
        name: my-java-quarkus
        resources: {}
status: {}
