apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-quarkus-quick-start
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-quarkus-quick-start
    app.kubernetes.io/part-of: my-quarkus-quick-start
  name: my-quarkus-quick-start
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: my-quarkus-quick-start
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: my-quarkus-quick-start
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-mcombi-tenant/my-quarkus-quick-start/my-quarkus-quick-start@sha256:e0e25b97f44d2a8e594906b3ee1d3b2467a791d98c424c49245e5ce6931aa7ad
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
