apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-quarkus-quick-start
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-quarkus-quick-start
    app.kubernetes.io/part-of: my-quarkus-quick-start
  name: my-quarkus-quick-start
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: my-quarkus-quick-start
status:
  loadBalancer: {}
